apps/django-tinymce-master/testtinymce/urls.py
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
from django.conf.urls import include, url

import tinymce.urls

admin.autodiscover()

urlpatterns = [
    url(r'^tinymce/', include(tinymce.urls)),
    url(r'^admin/', include(admin.site.urls)),
    #url(r'^%s(?P<path>.*)$' % settings.MEDIA_URL[1:], 
    #    'django.views.static.serve', {"document_root": settings.MEDIA_ROOT}),
]

urlpatterns += staticfiles_urlpatterns()

apps/django-tinymce-master/tinymce/urls.py
# Copyright (c) 2008 Joost Cassee
# Licensed under the terms of the MIT License (see LICENSE.txt)
from django.conf.urls import url

from tinymce import views

urlpatterns = [
    url(r'^spellchecker/$', views.spell_check, name='tinymce-spellcheck'),
    url(r'^flatpages_link_list/$', views.flatpages_link_list, name='tinymce-linklist'),
    url(r'^compressor/$', views.compressor, name='tinymce-compressor'),
    url(r'^filebrowser/$', views.filebrowser, name='tinymce-filebrowser'),
]

apps/post/urls.py
from django.conf.urls import url
from .views import home,crear_post_general,list_post_general,detail_post_general
from django.contrib.auth.decorators import login_required

urlpatterns =  [
	url(r'^$',home,name = "index"),
	url(r'^nueva_entrada/general/',login_required(crear_post_general),name = "crear_post_general"),
	url(r'^list/general/',list_post_general,name = "listar_post_general"),
	url(r'^detail/general/(?P<pk>[0-9]+)$',detail_post_general,name = "detail_post_general"),
	
]

openyourmind/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.auth.views import login,logout_then_login
from apps.post.views import home
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$',home,name = "index"),
    url(r'^post/',include('apps.post.urls', namespace = "post")),
    url(r'^accounts/login', login,{'template_name':'usuarios/login2.html'},name='login'),
 	url(r'^logout/',logout_then_login,name='logout'),
    url(r'^tinymce/', include('tinymce.urls')),
    #url(r'^media/(?P<path>.*)$','django.views.static.serve',{'document_root':settings.MEDIA_ROOT,}),
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

apps/post/models.py
from __future__ import unicode_literals
#from tinymce import models as tinymce_models
from django.db import models


class Comentario(models.Model):
	id = models.AutoField(primary_key = True)
	comentario = models.TextField()
	date = models.DateField(auto_now = False, auto_now_add = True)
	nombre = models.CharField(max_length = 200)
	email = models.EmailField()

	def __unicode__(self):
		return self.comentario

class Post(models.Model):
	id = models.AutoField(primary_key = True)
	#comentarios = models.ManyToManyField(Comentario)
	nueva_entrada = models.TextField()
	descripcion = models.TextField()
	titulo = models.CharField(max_length = 255)	
	categoria = models.CharField(max_length = 255)
	fecha = models.DateField(auto_now=False, auto_now_add=False)
	firma = models.CharField(max_length = 200)
	imagen = models.URLField(null = True)
	

	def __unicode__(self):
		return self.titulo

apps/post/forms.py
from django import forms
from .models import Post
from pagedown.widgets import PagedownWidget

class PostForm(forms.ModelForm):
	nueva_entrada = forms.CharField(widget=PagedownWidget(show_preview=True))
	class Meta:
		model = Post 
		fields = ['nueva_entrada','titulo','fecha','firma','categoria','descripcion','imagen',]
		labels = {'nueva_entrada':'Post','titulo':'Titulo','fecha':'Fecha de creacion',
				'firma':'Autor','categoria':'Categoria','descripcion':'Breve Descripcion','image':'URL'}
		widgets = {'titulo':forms.TextInput(),				
				'firma':forms.TextInput(),'fecha':forms.SelectDateWidget,
				'categoria':forms.TextInput(),'descripcion':forms.Textarea(),}
				#forms.TextInput(attrs = {'placeholder':'AA/MM/DD'})

apps/post/views.py
from django.shortcuts import render,redirect
from .models import Post
from .forms import PostForm
from django.http import HttpResponse,HttpResponseNotFound
#from django.views.generic import CreateView,DeleteView,UpdateView,ListView
from django.core.urlresolvers import reverse_lazy

def home(request):
	post = Post.objects.all()
	context = {'post':post}
	return render(request,'post/base.html',context)


############################### POST GENERALES ####################################
def crear_post_general(request):
	if request.method == 'POST':
		form = PostForm(request.POST or None, request.FILES or None)
		if form.is_valid():
			form.save()
			return redirect('post:index')		
	else:
		form = PostForm()

	return render(request,'post/general/crear_post_general.html',{'form':form})

def list_post_general(request):
	post = Post.objects.filter(categoria = "General")
	context = {'post':post,}
	return render(request,'post/general/listar_post_general.html',context)


def detail_post_general(request,pk):
	post = Post.objects.filter(id=pk)
	post2 = post[0] if len(post) == 1 else None
	if post2 is not None:
		context = {
			'post2':post2
		}
		return render(request,'post/general/detail_general.html',context)
	else:
		return HttpResponseNotFound('No existe el post')

#############################################################################################

############################### POST TECNOLOGIA ####################################

def list_post_tecnologia(request):
    post = Post.objects.filter(categoria = "Tecnologia")
    context = {'post':post,}
    return render(request,'post/listar_post_tecnologia.html',context)

#############################################################################################

############################### POST VIDEOJUEGOS ####################################
def list_post_videojuegos(request):
    post = Post.objects.filter(categoria = "Videojuegos")
    context = {'post':post,}
    return render(request,'post/listar_post_videojuegos.html',context)

#############################################################################################


############################### POST GENERALES ####################################
def list_post_programacion(request):
    post = Post.objects.filter(categoria = "Programacion")
    context = {'post':post,}
    return render(request,'post/listar_post_programacion',context)






#############################################################################################

templates/post/general/crear_post_general.html
{% extends 'post/static.html' %}
{% load staticfiles %}
{% load static from staticfiles %}

<!DOCTYPE html>
<html>
{% block title %}<title>Developer.pe</title>{%  endblock %}
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body,h1,h2,h3,h4,h5 {font-family: "Raleway", sans-serif}
</style>
<head class="w3-light-grey">
{% block head %}
	<div >
	  <div class="w3-bar w3-left-align w3-large">
	    <a class="w3-bar-item w3-button w3-right w3-hide-large w3-hover-white w3-large w3-theme-l1" </a>
	    <a href="{% url 'post:index' %}" class="w3-bar-item w3-button w3-theme-l1">Home</a>
	    <a href="{% url 'post:listar_post_general' %}" class="w3-bar-item w3-button w3-hide-small w3-hover-white">Post</a>  		
	    <a href="{% url 'post:crear_post_general' %}" class="w3-bar-item w3-button w3-hide-small w3-hover-white">Nueva entrada</a>
	    
	  </div>
	</div>
	<header class="w3-container w3-center"> 
	  <h1><b>Developer.pe</b></h1>
	  <p>Bienvenidos<span class="w3-tag"></span></p>
	</header>
{% endblock %}
</head>
<body class="w3-light-grey">
{% block body %}
	<form method="post" enctype="multipart/form-data">
		{% csrf_token %}
		<div class="w3-container w3-input">
			<label>Titulo {{ form.titulo }}</label>
			<label>Fecha {{ form.fecha }}</label>
			<label>Genero {{ form.categoria }}</label><br><br>
			<div class="w3-cell-row">
				<div class="w3-cell">
					<div class="w3-container"> 
						<label>Breve descripción</label>	
					</div>
					{{ form.descripcion }}	
				</div>							 
				 <div class="w3-cell">
				 	<div class="w3-container">
				 		<label>Post</label>	
				 	</div>
				 	{{ form.nueva_entrada }}
				 </div>	 
			</div><br>
			<label >URL {{ form.imagen }} <br></label><br>
			<label >Firma {{ form.firma }}</label>
		</div><br>
		<div class="w3-container">
			<button class="w3-button w3-black w3-padding-large w3-margin-bottom" type="submit">Crear</button>
		</div>
		
	</form>
	<!-- Footer -->
	<footer class="w3-container w3-dark-grey w3-padding-32 w3-margin-top">
	  <button class="w3-button w3-black w3-disabled w3-padding-large w3-margin-bottom">Previous</button>
	  <button class="w3-button w3-black w3-padding-large w3-margin-bottom">Next »</button>
	  <p class="w3-center">OpenYourMind</p>
	  <div class="w3-container w3-center">
	  	  <p>Encuentrame tambien: </p>
		  <a href="https://www.facebook.com/openmindsan/"  target="_blank" class="icon-facebook2"></a>
		  <a href="https://twitter.com/OpenYourMindSan?lang=es"  target="_blank" class="icon-twitter"></a>
		  <a href="https://www.youtube.com/channel/UCOzf2U3BTng85gsFJHvIInQ?view_as=public"  target="_blank" class="icon-youtube2"></a>
	  </div>  
	</footer>
{% endblock %}
</body>
</html>

templates/post/general/detail_general.html
{% extends 'post/static.html' %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
 
<head>
	    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-111610469-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-111610469-1');
    </script>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="{% static 'css/w3.css' %}">
<link rel="stylesheet" href="{% static 'css/fonts/style.css' %}">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
<style>
body,h1,h2,h3,h4,h5 {font-family: "Raleway", sans-serif}
</style>
<title>{{ post2.titulo }}</title>
<div>

	  <div class="w3-bar w3-left-align w3-large">
	    <a class="w3-bar-item w3-button w3-right w3-hide-large w3-hover-white w3-large w3-theme-l1" </a>
	    <a href="{% url 'post:index' %}" class="w3-bar-item w3-button w3-theme-l1">Home</a>
	    <a href="{% url 'post:listar_post_general' %}" class="w3-bar-item w3-button w3-hide-small w3-hover-white">Post</a>  
	    <a href="{% url 'post:crear_post_general' %}" class="w3-bar-item w3-button w3-hide-small w3-hover-white">Nueva entrada</a>
	  </div>
	</div>
</head>


<body class="w3-light-grey">
<div class="w3-content" style="max-width:1400px">
	<div class="w3-card-4 w3-margin w3-white">
		<div class="w3-container">
			<h3>{{ post2.titulo }} ,<span class="w3-opacity">{{ post2.fecha }}</span></h3>
			<p>{{ post2.nueva_entrada }}</p>	
			<img src="{{ post2.imagen }}" class="img-responsive" />				
			<p class="w3-tag w3-teal">{{ post2.genero.genero }}</p>			
		</div>
	</div>
	
</div>


<!-- Footer -->
<footer class="w3-container w3-dark-grey w3-padding-32 w3-margin-top w3-content " style="max-width:1360px">
  <button class="w3-button w3-black w3-disabled w3-padding-large w3-margin-bottom">Previous</button>
  <button class="w3-button w3-black w3-padding-large w3-margin-bottom">Next »</button>
  <p class="w3-center">OpenYourMind</p>
  <div class="w3-container w3-center">
  	  <p>Encuentrame tambien: </p>
	  <a href="https://www.facebook.com/openmindsan/"  target="_blank" class="icon-facebook2"></a>
	  <a href="https://twitter.com/OpenYourMindSan?lang=es"  target="_blank" class="icon-twitter"></a>
	  <a href="https://www.youtube.com/channel/UCOzf2U3BTng85gsFJHvIInQ?view_as=public"  target="_blank" class="icon-youtube2"></a>
  </div>  
</footer>
</body>
</html>

templates/post/general/listar_post_general.html
{% extends 'post/static.html' %}
{% load staticfiles %}
<!DOCTYPE html>
<html>
{% block title %}
<title>Developer.pe</title>
{% endblock %}
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
 
<style>
body,h1,h2,h3,h4,h5 {font-family: "Raleway", sans-serif}
</style>
<head class="w3-light-grey">
	{% block head %}
	    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-111610469-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-111610469-1');
    </script>
	<div >
	  <div class="w3-bar w3-left-align w3-large">
	    <a class="w3-bar-item w3-button w3-right w3-hide-large w3-hover-white w3-large w3-theme-l1" </a>
	    <a href="{% url 'index' %}" class="w3-bar-item w3-button w3-theme-l1">Home</a>
	    <a href="{% url 'post:listar_post_general' %}" class="w3-bar-item w3-button w3-hide-small w3-hover-white">Post</a>
	    {% if user.is_authenticated %}
            {% if user.is_superuser %}
	            <a href="{% url 'post:crear_post_general' %}" class="w3-bar-item w3-button w3-hide-small w3-hover-white">Nueva entrada</a>
	        {% endif %}
	    {% endif %}
	  </div>
	</div>
	<header class="w3-container w3-center"> 
	  <h1><b>Developer.pe</b></h1>
	  <p>Bienvenidos<span class="w3-tag"></span></p>
	</header>
	{% endblock %}
</head>
<body class="w3-light-grey">
{% block body %}
	{% if post %}
	{% for post in post %}
		<div class="w3-content" style="max-width:1400px">	
			<div class="w3-card-4 w3-margin w3-white">  
			  <div class="w3-container">
			    <h3>{{ post.titulo }} ,<span class="w3-opacity">{{ post.fecha }}</span></h3>
			    </div>
			    <div class="w3-container">		    
			      <p>{{ post.nueva_entrada }}</p>
			      <p class="w3-tag w3-teal">{{ post.genero.genero }}</p>  
			      <div >
			        <a href="{% url 'post:detail_post_general' post.id %}"><p><button class="w3-button w3-padding-large w3-light-grey w3-border"><b>READ MORE »</b></button></p></a>
			      </div>		        
			     </div>
			  </div>
			</div>
		</div>
	{% endfor %}
	{% endif %}
	<!-- Footer -->
	<footer class="w3-container w3-dark-grey w3-padding-32 w3-margin-top">
	  <button class="w3-button w3-black w3-disabled w3-padding-large w3-margin-bottom">Previous</button>
	  <button class="w3-button w3-black w3-padding-large w3-margin-bottom">Next »</button>
	  <p class="w3-center">OpenYourMind</p>
	  <div class="w3-container w3-center">
	  	  <p>Encuentrame tambien: </p>
		  <a href="https://www.facebook.com/openmindsan/"  target="_blank" class="icon-facebook2"></a>
		  <a href="https://twitter.com/OpenYourMindSan?lang=es"  target="_blank" class="icon-twitter"></a>
		  <a href="https://www.youtube.com/channel/UCOzf2U3BTng85gsFJHvIInQ?view_as=public"  target="_blank" class="icon-youtube2"></a>
	  </div>  
	</footer>
{% endblock %}
</body>
</html>

templates/post/general/new_dGmail.html
<!DOCTYPE html>
<html lang="es">
  <head>
      <!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-111610469-2"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-111610469-2');
</script>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title> - Developer.pe</title>
    <!-- Bootstrap core CSS -->
    <link href="../../../../../static/general/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="../../../../../static/general/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- Custom styles for this template -->
    <link href="../../../../../static/general/css/detail.css" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="../../../../../static/css/w3.css">
    <link rel="shortcut icon" href="imagenes/favicon.ico" type="image/x-icon">
    <link rel="icon" href="../.././../../../static/imagenes/favicon.ico" type="image/x-icon">

  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
      <div class="container">
        <a class="navbar-brand" href="../../../../../index.html">DEVELOPER.PE</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">MENU
          <i class="fa fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#inicio">Inicio</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="../../listar_post_general.html">Post</a>
            </li>            
          </ul>
        </div>
      </div>
    </nav>

    <!-- Page Header -->
    <header class="masthead" id="inicio"> 
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <div class="post-heading">
              <h1>Este sera el nuevo diseño de Gmail</h1>
              <h3 class="subheading">Tras años sin sufrir algun cambio estetico, Gmail estrenará un nuevo diseño las proximas semanas</h3>
              <span class="meta">Creado por: Oliver Sandoval,            
                12/04/2018</span>
            </div>
          </div>
        </div>
      </div>
    </header>

    <!-- Post Content -->
    <article>
      <div class="container" >
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <p ALIGN="justify">El dia de ayer Google anunciaba un nuevo diseño para su plataforma Gmail que seria lanzado en las proximas semanas, y tan solo a unas horas después de esté se han filtrado imagenes del nuevo diseño gracias al portal <a href="https://www.theverge.com/2018/4/12/17227974/google-gmail-design-features-update-2018-redesign"><em>The Verge</em></a></p> 
            
            <img class="img-fluid" src="../../../../../static/imagenes/general/new_gmail1.png" alt="">
            
              
            <p ALIGN="justify">Esta nueva version implementa respuestas inteligentes para Gmail en la web, la misma de Gmail móvil que brinda sugerencias para responder rapidamente  a los correos electronicos.</p> 
            <img class="img-fluid" src="../../../../../static/imagenes/general/gmaildesing_lateralbar.png" alt="">
                       
            <h2 class="section-heading">GMail recibe una nueva barra lateral</h2>
            <p ALIGN="justify">Es una de las funciones que más llama la atencion ya que al lado derecho tendremos un menu que incorpora otros servicios de Google, como Google Keeper para crear notas, o Google calendar para ver tu agenda. Esta sea quizas la parte mas util del rediseño ya que con estas herramientas podras programar reuniones, o ver cuándo estes libre para cualquier otra actividad.</p>
            
            <img class="img-fluid" src="../../../../../static/imagenes/general/gmaildesign_2.png" alt="">                
           
            <h2 class="section-heading">Tres maneras de visualizar el nuevo Gmail </h2>
            <p ALIGN="justify">Google ofrecer tres nuevos diseños para elegir, incluida una vista predeterminada que destaca archivos adjuntos como ducumentos y fotos, una vista comoda que no resalta archivos adjuntos y finalmente una vista compacta que aumenta la cantidad de mensajes que puede verse en una sola pagina. La ultima vista es la más similar al diseño exiaaaastente de Gmail, lo quae permite a los usuarios existentes mantener un diseño similar</p>
            
             <img class="img-fluid " src="../../../../../static/imagenes/general/Gmail-rediseño.png" alt="">
              <img class="img-fluid " src="../../../../../static/imagenes/general/Gmal-rediseñocompact.png" alt="">
            <p ALIGN="justify">Como se puede observar los cambios no son tan abruptos asi que no parece que Google este listo para cambiar radicalmente Gmail a sus niveles de bandeja de entrada, por lo que Inbox(plataforma de Google) seguira existiendo</p>                   
           
             <p ALIGN="justify"> Google I/O, conferencia anual para desarrolladores, <strong>será el proximo 8 de mayo en Mountain View,</strong>y es razonble suponer que este nuevo diseño de Gmail será parte de los muchos anuncios de esta feria</p>
         
          </div>
        </div>
      </div>
    </article>

    <hr>

    <!-- Footer -->
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <ul class="list-inline text-center">
              <li class="list-inline-item">
                <a href="https://twitter.com/Developerpepiur"  target="_blank">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="https://www.facebook.com/developerper/"  target="_blank">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="https://www.youtube.com/channel/UCOzf2U3BTng85gsFJHvIInQ?view_as=public"  target="_blank">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-youtube fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
            </ul>
            <p class="copyright text-muted">Copyright &copy; Developer.pe</p>
          </div>
        </div>
      </div>
    </footer>
<!-- Bootstrap core JavaScript -->
    <script src="../../../../static/general/vendor/jquery/jquery.min.js"></script>
    <script src="../../../../static/general/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Custom scripts for this template -->
    <script src="../../../../static/general/js/clean-blog.min.js"></script>
    <script src="../../../../static/base/vendor/jquery-easing/jquery.easing.min.js"></script>  
    <script src="../../../../static/base/js/creative.min.js"></script>
      
          <div id="wpac-comment"></div>
        <script type="text/javascript">
            wpac_init = window.wpac_init || [];
            wpac_init.push({widget: 'Comment', id: 10382});
            (function() {
                if ('WIDGETPACK_LOADED' in window) return;
                WIDGETPACK_LOADED = true;
                var mc = document.createElement('script');
                mc.type = 'text/javascript';
                mc.async = true;
                mc.src = 'https://embed.widgetpack.com/widget.js';
                var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(mc, s.nextSibling);
            })();
        </script>
  </body>

</html>